# main_cli.py
"""
CLI that generates 3D models, saves them, and opens in FreeCAD GUI.
"""

import sys
import os
import logging
import subprocess
import tempfile
from ollama_generator_mac import OllamaGenerator, create_generator
from cad_bridge import CADBridge, get_bridge
from code_executor import CodeExecutor

logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s [%(name)s] %(message)s',
    datefmt='%H:%M:%S'
)
logger = logging.getLogger("Main")

# Colors
G = "\033[92m"
R = "\033[91m"
Y = "\033[93m"
C = "\033[96m"
B = "\033[1m"
X = "\033[0m"

# ── Output directory ──
OUTPUT_DIR = os.path.expanduser("~/FreeCAD_Generated")
os.makedirs(OUTPUT_DIR, exist_ok=True)


def find_freecad_app() -> str:
    """Find FreeCAD application on macOS."""
    candidates = [
        "/Applications/FreeCAD.app",
        "/Applications/FreeCAD_0.21.app",
        "/Applications/FreeCAD_0.22.app",
        "/Applications/FreeCAD_weekly.app",
        os.path.expanduser("~/Applications/FreeCAD.app"),
    ]
    for path in candidates:
        if os.path.exists(path):
            return path
    return ""


def wrap_code_as_macro(code: str, part_name: str = "AI_Model") -> str:
    """
    Wrap the generated code into a complete FreeCAD macro
    that creates a document, runs the code, and saves the result.
    """
    save_path = os.path.join(OUTPUT_DIR, f"{part_name}.FCStd")
    step_path = os.path.join(OUTPUT_DIR, f"{part_name}.step")

    macro = f'''# ══════════════════════════════════════════════════════
# FreeCAD Macro — Auto-Generated by AI Model Generator
# ══════════════════════════════════════════════════════
#
# To run:
#   1. Open FreeCAD
#   2. Macro → Execute Macro → select this file
#   OR
#   3. Paste into FreeCAD Python Console (View → Panels → Python Console)
#

import FreeCAD
import Part

# ── Create document ──
doc = FreeCAD.newDocument("{part_name}")

# ── Helpers ──
Vector = FreeCAD.Vector
Placement = FreeCAD.Placement
Rotation = FreeCAD.Rotation

def update():
    doc.recompute()

def save(filepath=None):
    if filepath:
        doc.saveAs(filepath)

# ══════════════════════════════════════════
# YOUR 3D MODEL
# ══════════════════════════════════════════

{code}

# ══════════════════════════════════════════
# SAVE FILES
# ══════════════════════════════════════════

import os
os.makedirs(r"{OUTPUT_DIR}", exist_ok=True)

# Save FreeCAD native
doc.saveAs(r"{save_path}")
print(f"Saved: {save_path}")

# Save STEP file
try:
    __objs__ = []
    for obj in doc.Objects:
        if hasattr(obj, "Shape") and hasattr(obj, "Visibility"):
            if obj.Visibility:
                __objs__.append(obj)
    if not __objs__:
        __objs__ = [o for o in doc.Objects if hasattr(o, "Shape")]
    if __objs__:
        Part.export(__objs__, r"{step_path}")
        print(f"Saved STEP: {step_path}")
except Exception as e:
    print(f"STEP export skipped: {{e}}")

# Fit view
try:
    import FreeCADGui
    FreeCADGui.ActiveDocument.ActiveView.fitAll()
except Exception:
    pass

print("\\n🎉 Model created successfully!")
'''
    return macro


def save_macro_file(code: str, name: str) -> tuple:
    """Save code as .FCMacro and .py files. Returns (macro_path, py_path)."""
    # Clean name
    safe = "".join(c if c.isalnum() or c in "-_ " else "_" for c in name)
    safe = safe.strip().replace(" ", "_")[:40] or "Model"

    macro_content = wrap_code_as_macro(code, safe)

    macro_path = os.path.join(OUTPUT_DIR, f"{safe}.FCMacro")
    py_path = os.path.join(OUTPUT_DIR, f"{safe}.py")

    with open(macro_path, "w") as f:
        f.write(macro_content)

    with open(py_path, "w") as f:
        f.write(macro_content)

    return macro_path, py_path


def open_in_freecad(macro_path: str) -> bool:
    """Open macro file in FreeCAD."""
    app = find_freecad_app()
    if app:
        try:
            subprocess.Popen(["open", "-a", app, macro_path])
            return True
        except Exception:
            pass

    # Fallback: try generic open
    try:
        subprocess.Popen(["open", macro_path])
        return True
    except Exception:
        return False


def run_in_freecad_headless(py_path: str) -> bool:
    """Run script using FreeCAD's command-line mode."""
    app = find_freecad_app()
    if not app:
        return False

    # Try FreeCADCmd (headless mode)
    cmd_paths = [
        os.path.join(app, "Contents/Resources/bin/FreeCADCmd"),
        os.path.join(app, "Contents/bin/FreeCADCmd"),
        os.path.join(app, "Contents/MacOS/FreeCADCmd"),
        "FreeCADCmd",
    ]

    for cmd in cmd_paths:
        if os.path.exists(cmd) or cmd == "FreeCADCmd":
            try:
                print(f"{Y}Running headless: {cmd}{X}")
                result = subprocess.run(
                    [cmd, "--console", "--run", py_path],
                    capture_output=True,
                    text=True,
                    timeout=30,
                )
                print(result.stdout)
                if result.stderr:
                    print(f"{Y}{result.stderr}{X}")
                return result.returncode == 0
            except (FileNotFoundError, subprocess.TimeoutExpired):
                continue
    return False


def print_banner():
    print(f"""{C}{B}
╔══════════════════════════════════════════════════╗
║   🏭  3D Model Generator                        ║
║   Ollama → FreeCAD                               ║
║                                                  ║
║   Describe a part → Get a 3D model               ║
╚══════════════════════════════════════════════════╝{X}
""")


def print_help():
    print(f"""
{B}Commands:{X}
  {C}<description>{X}          → Generate a 3D model
  {C}/add <desc>{X}            → Modify (continues conversation)
  {C}/code{X}                  → Show last generated code
  {C}/open{X}                  → Open last model in FreeCAD
  {C}/run{X}                   → Run headless (saves files)
  {C}/dir{X}                   → Open output folder
  {C}/paste{X}                 → Show code to paste into FreeCAD console
  {C}/model <name>{X}          → Switch Ollama model
  {C}/models{X}                → List available models
  {C}/retry{X}                 → Retry last prompt
  {C}/clear{X}                 → Clear history
  {C}/help{X}                  → This help
  {C}/quit{X}                  → Exit

{B}Output folder:{X} {OUTPUT_DIR}

{B}Examples:{X}
  • Create a cube with 50mm sides
  • Make a plate 200x100x10mm with 4 corner holes
  • Build a cylinder radius 25mm height 80mm
  • Create an L-bracket with fillets
  • Make a hollow pipe OD=60mm ID=50mm length=150mm
""")


def main():
    print_banner()
    print(f"{Y}Initializing...{X}")

    # Check if FreeCAD is installed
    freecad_app = find_freecad_app()
    if freecad_app:
        print(f"{G}✅ FreeCAD found: {freecad_app}{X}")
    else:
        print(f"{Y}⚠️  FreeCAD not found in /Applications{X}")
        print(f"{Y}   Install: brew install --cask freecad{X}")
        print(f"{Y}   Models will be saved as macros you can open later{X}")

    # Initialize bridge (for in-memory execution)
    bridge = get_bridge()
    bridge_connected = bridge.connect()
    if bridge_connected:
        print(f"{G}✅ FreeCAD Python engine ready{X}")
    else:
        print(f"{Y}⚠️  FreeCAD Python not available (will save macros only){X}")

    # Initialize Ollama
    try:
        model = "qwen3-coder:480b-cloud"
        generator = create_generator(model)
    except Exception as e:
        print(f"{R}ERROR: Ollama not available: {e}{X}")
        print("Run: ollama serve")
        sys.exit(1)

    print(f"{G}✅ Ollama ready: {model}{X}")
    print(f"{G}✅ Output: {OUTPUT_DIR}{X}")

    # Executor (if bridge connected)
    executor = None
    if bridge_connected:
        executor = CodeExecutor(bridge)

    print_help()

    last_code = ""
    last_prompt = ""
    last_macro_path = ""
    last_py_path = ""
    counter = 0

    while True:
        try:
            user_input = input(f"\n{B}{C}🏭 Describe ▶ {X}").strip()
            if not user_input:
                continue

            # ── Commands ──
            if user_input.startswith("/"):
                parts = user_input.split(maxsplit=1)
                cmd = parts[0].lower()
                arg = parts[1] if len(parts) > 1 else ""

                if cmd in ("/quit", "/exit", "/q"):
                    print(f"{Y}Goodbye! 👋{X}")
                    break

                elif cmd == "/help":
                    print_help()

                elif cmd == "/code":
                    if last_code:
                        print(f"\n{B}Last generated code:{X}")
                        print(f"{C}{'─' * 50}")
                        for i, line in enumerate(last_code.split('\n'), 1):
                            print(f"  {i:3d} │ {line}")
                        print(f"{'─' * 50}{X}")
                    else:
                        print("No code yet.")

                elif cmd == "/paste":
                    if last_code:
                        print(f"\n{B}Paste this into FreeCAD's Python Console:{X}")
                        print(f"{C}{'═' * 50}")
                        macro = wrap_code_as_macro(last_code, f"Model_{counter}")
                        print(macro)
                        print(f"{'═' * 50}{X}")
                        print(f"\n{Y}In FreeCAD: View → Panels → Python Console{X}")
                    else:
                        print("No code yet.")

                elif cmd == "/open":
                    if last_macro_path:
                        if open_in_freecad(last_macro_path):
                            print(f"{G}✅ Opening FreeCAD...{X}")
                            print(f"\n{B}In FreeCAD, run the macro:{X}")
                            print(f"  1. Macro → Macros...")
                            print(f"  2. Change folder to: {OUTPUT_DIR}")
                            print(f"  3. Select your file")
                            print(f"  4. Click {B}Execute{X}")
                        else:
                            print(f"{Y}Cannot auto-open.{X}")
                            print(f"Open manually: {last_macro_path}")
                    else:
                        print("No macro generated yet.")

                elif cmd == "/run":
                    if last_py_path:
                        if not run_in_freecad_headless(last_py_path):
                            print(f"{Y}Headless mode not available.{X}")
                            print(f"Use /open or /paste instead.")
                    else:
                        print("No script yet.")

                elif cmd == "/dir":
                    subprocess.Popen(["open", OUTPUT_DIR])
                    print(f"{G}Opened: {OUTPUT_DIR}{X}")

                elif cmd == "/model":
                    if arg:
                        try:
                            generator.switch_model(arg)
                            print(f"{G}Switched to: {arg}{X}")
                        except Exception as e:
                            print(f"{R}Failed: {e}{X}")
                    else:
                        print(f"Current: {generator.model}")

                elif cmd == "/models":
                    models = generator.get_available_models()
                    print(f"\n{B}Available models:{X}")
                    for m in models:
                        cur = " ← current" if m == generator.model else ""
                        print(f"  • {m}{G}{cur}{X}")

                elif cmd == "/add":
                    if not arg:
                        print("Usage: /add <feature description>")
                        continue

                    print(f"{Y}🤖 Generating...{X}")
                    code = generator.modify_existing(arg)
                    last_code = code
                    counter += 1

                    # Show
                    print(f"\n{B}Generated:{X}")
                    print(f"{C}{'─' * 50}")
                    for i, line in enumerate(code.split('\n'), 1):
                        print(f"  {i:3d} │ {line}")
                    print(f"{'─' * 50}{X}")

                    # Save
                    name = f"Modified_{counter}"
                    last_macro_path, last_py_path = save_macro_file(code, name)
                    print(f"{G}📁 Saved: {last_macro_path}{X}")

                    # Execute in memory if bridge available
                    if executor and bridge_connected:
                        ok, msg, err = executor.execute(code)
                        if ok:
                            print(f"{G}✅ {msg}{X}")

                elif cmd == "/retry":
                    if last_prompt:
                        user_input = last_prompt
                    else:
                        print("Nothing to retry.")
                        continue

                elif cmd == "/clear":
                    generator.clear_history()
                    print(f"{G}Cleared.{X}")

                else:
                    print(f"Unknown: {cmd}. Type /help")

                if cmd != "/retry":
                    continue

            # ═══════════════════════════════════════════
            # GENERATE MODEL
            # ═══════════════════════════════════════════
            last_prompt = user_input
            counter += 1

            # Generate code with Ollama
            print(f"{Y}🤖 Generating FreeCAD code...{X}")
            code = generator.generate_code(user_input)
            last_code = code

            # Show code
            print(f"\n{B}Generated Code:{X}")
            print(f"{C}{'─' * 50}")
            for i, line in enumerate(code.split('\n'), 1):
                print(f"  {i:3d} │ {line}")
            print(f"{'─' * 50}{X}")

            # Create name
            words = user_input.split()[:4]
            part_name = "_".join(
                w for w in words
                if w.lower() not in ("a", "an", "the", "with", "and")
            )[:30] or f"Model_{counter}"

            # Save macro files
            last_macro_path, last_py_path = save_macro_file(code, part_name)

            # Execute in memory if possible
            if executor and bridge_connected:
                bridge.create_new_part(part_name)
                ok, msg, err = executor.execute(code)
                if ok:
                    print(f"{G}✅ In-memory execution: {msg}{X}")
                else:
                    print(f"{Y}⚠️ In-memory: {msg} (macro saved anyway){X}")

            # Success output
            print(f"\n{G}{'═' * 50}")
            print(f"{B}🎉 MODEL GENERATED!{X}")
            print(f"{G}{'═' * 50}{X}")
            print(f"\n{B}Files:{X}")
            print(f"  📄 Macro:  {C}{last_macro_path}{X}")
            print(f"  📄 Script: {C}{last_py_path}{X}")

            print(f"\n{B}To view your 3D model, choose:{X}")
            print(f"  {C}1{X} → Open FreeCAD GUI (see it visually)")
            print(f"  {C}2{X} → Copy paste-ready code for FreeCAD console")
            print(f"  {C}3{X} → Open output folder")
            print(f"  {C}Enter{X} → Continue generating")

            choice = input(f"\n{Y}[1/2/3/Enter]: {X}").strip()

            if choice == "1":
                print(f"\n{Y}Opening FreeCAD...{X}")
                if open_in_freecad(last_macro_path):
                    print(f"""
{G}{'═' * 50}
  FreeCAD is opening!

  To see your model:
  ┌─────────────────────────────────────────┐
  │  1. In FreeCAD menu: Macro → Macros...  │
  │  2. Click "User macros location" ...    │
  │  3. Navigate to:                        │
  │     {OUTPUT_DIR}
  │  4. Select: {os.path.basename(last_macro_path)}
  │  5. Click [Execute]                     │
  │                                         │
  │  🎉 Your 3D model appears!             │
  └─────────────────────────────────────────┘
{'═' * 50}{X}""")
                else:
                    print(f"{Y}FreeCAD not found. Install:{X}")
                    print(f"  brew install --cask freecad")

            elif choice == "2":
                print(f"\n{B}Copy everything below and paste into FreeCAD's Python Console:{X}")
                print(f"{Y}(In FreeCAD: View → Panels → Python Console){X}\n")
                print(f"{C}{'═' * 50}")
                print(wrap_code_as_macro(code, part_name))
                print(f"{'═' * 50}{X}")

            elif choice == "3":
                subprocess.Popen(["open", OUTPUT_DIR])
                print(f"{G}Opened: {OUTPUT_DIR}{X}")

        except KeyboardInterrupt:
            print(f"\n{Y}/quit to exit{X}")
        except Exception as e:
            print(f"{R}Error: {e}{X}")
            logger.exception("Error")


if __name__ == "__main__":
    main()